from nnUtils import *

model = Sequential([
    SpatialConvolution(8,11,1,4,1, padding='VALID', name='conv11', bias=False),
    SpatialConvolution(96,1,11,1,4, padding='VALID', name='conv12', bias=False),
    BatchNormalization(name='batch12'),
    ReLU(),
    SpatialMaxPooling(3,3,2,2, padding='VALID', name='pool1'),
    LocalResposeNormalize(5, 1e-04, 0.75, name='lrn1'),
    SpatialConvolution(40,5,1, padding='VALID', name='conv21', bias=False),
    SpatialConvolution(256,1,5, padding='VALID', name='conv22', bias=False),
    BatchNormalization(name='batch22'),
    ReLU(),
    SpatialMaxPooling(3,3,2,2, padding='VALID', name='pool2'),
    LocalResposeNormalize(5, 1e-04, 0.75, name='lrn2'),
    SpatialConvolution(60,3,1, padding='VALID', name='conv31', bias=False),
    SpatialConvolution(384,1,3, padding='VALID', name='conv32', bias=False),
    BatchNormalization(name='batch32'),
    ReLU(),
    SpatialConvolution(100,3,1, padding='VALID', name='conv41', bias=False),
    SpatialConvolution(384,1,3, padding='VALID', name='conv42', bias=False),
    BatchNormalization(name='batch42'),
    ReLU(),
    SpatialConvolution(200,3,1, padding='VALID', name='conv51', bias=False),
    SpatialConvolution(256,1,3, padding='VALID', name='conv52', bias=False),
    BatchNormalization(name='batch52'),
    ReLU(),
    SpatialMaxPooling(3,3,2,2, padding='VALID', name='pool5'),
    Affine(4096, name='fc1', bias=True),
    ReLU(),
    Dropout(0.5),
    Affine(4096, name='fc2', bias=True),
    ReLU(),
    Dropout(0.5),
    Affine(1000, name='fc3', bias=True)
])
