from nnUtils import *

model = Sequential([
    SpatialConvolution(64,3,3, padding='SAME', name='conv1'),
    BatchNormalization(name='batch1'),
    ReLU(name='rrelu1'),
    SpatialConvolution(64,3,3, padding='SAME', name='conv2'),
    BatchNormalization(name='batch2'),
    ReLU(name='rrelu2'),
    SpatialConvolution(128,3,3,2,2, padding='SAME', name='conv3'),
    BatchNormalization(name='batch3'),
    ReLU(name='rrelu3'),
    SpatialConvolution(128,3,3, padding='SAME', name='conv4'),
    BatchNormalization(name='batch4'),
    ReLU(name='rrelu4'),
    SpatialConvolution(256,3,3,2,2, padding='SAME', name='conv5'),
    BatchNormalization(name='batch5'),
    ReLU(name='rrelu5'),
    SpatialConvolution(256,3,3, padding='SAME', name='conv6'),
    BatchNormalization(name='batch6'),
    ReLU(name='rrelu6'),
    SpatialConvolution(512,3,3,2,2, padding='SAME', name='conv7'),
    BatchNormalization(name='batch7'),
    ReLU(name='rrelu7'),
    SpatialConvolution(512,3,3, padding='SAME', name='conv8'),
    BatchNormalization(name='batch8'),
    ReLU(name='rrelu8'),
    SpatialConvolution(512,3,3,2,2, padding='SAME', name='conv9'),
    BatchNormalization(name='batch9'),
    ReLU(name='rrelu9'),
    SpatialConvolution(512,3,3, padding='SAME', name='conv10'),
    BatchNormalization(name='batch10'),
    ReLU(name='rrelu10'),
    SpatialAveragePooling(7,7,1,1, name='pool10'),
    Affine(1000, name='fc11')
])